/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.awesomepiece.pl.swig;

public class GameServerHandler {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GameServerHandler(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GameServerHandler obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nlibJNI.delete_GameServerHandler(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    nlibJNI.GameServerHandler_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    nlibJNI.GameServerHandler_change_ownership(this, swigCPtr, true);
  }

  public void HandleConnected(SWIGTYPE_p_GameSessionInterface session) {
    nlibJNI.GameServerHandler_HandleConnected(swigCPtr, this, SWIGTYPE_p_GameSessionInterface.getCPtr(session));
  }

  public void HandlePacket(SWIGTYPE_p_GameSessionInterface session, SWIGTYPE_p_GamePacket packet) {
    nlibJNI.GameServerHandler_HandlePacket(swigCPtr, this, SWIGTYPE_p_GameSessionInterface.getCPtr(session), SWIGTYPE_p_GamePacket.getCPtr(packet));
  }

  public void HandleDisconnected(SWIGTYPE_p_GameSessionInterface session) {
    nlibJNI.GameServerHandler_HandleDisconnected(swigCPtr, this, SWIGTYPE_p_GameSessionInterface.getCPtr(session));
  }

  public GameServerHandler() {
    this(nlibJNI.new_GameServerHandler(), true);
    nlibJNI.GameServerHandler_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
