/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.awesomepiece.pl.swig;

public class GameClientInterface {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GameClientInterface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GameClientInterface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nlibJNI.delete_GameClientInterface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void WritePacket(SWIGTYPE_p_byte bytes, SWIGTYPE_p_uint32_t length) {
    nlibJNI.GameClientInterface_WritePacket(swigCPtr, this, SWIGTYPE_p_byte.getCPtr(bytes), SWIGTYPE_p_uint32_t.getCPtr(length));
  }

  public boolean Connect(GameConfig config) {
    return nlibJNI.GameClientInterface_Connect(swigCPtr, this, GameConfig.getCPtr(config), config);
  }

  public boolean IsConnected() {
    return nlibJNI.GameClientInterface_IsConnected(swigCPtr, this);
  }

  public void Disconnect() {
    nlibJNI.GameClientInterface_Disconnect(swigCPtr, this);
  }

}
