/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.awesomepiece.pl.swig;

public class GameServerInterface {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GameServerInterface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GameServerInterface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nlibJNI.delete_GameServerInterface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean Listen(GameConfig config) {
    return nlibJNI.GameServerInterface_Listen(swigCPtr, this, GameConfig.getCPtr(config), config);
  }

}
