/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.awesomepiece.pl.swig;

public class GameClientFactory {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GameClientFactory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GameClientFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nlibJNI.delete_GameClientFactory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static GameClientInterface Create(GameClientHandler handler) {
    long cPtr = nlibJNI.GameClientFactory_Create(GameClientHandler.getCPtr(handler), handler);
    return (cPtr == 0) ? null : new GameClientInterface(cPtr, false);
  }

  public GameClientFactory() {
    this(nlibJNI.new_GameClientFactory(), true);
  }

}
