/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.awesomepiece.pl.swig;

public class GameServerFactory {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GameServerFactory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GameServerFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nlibJNI.delete_GameServerFactory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static GameServerInterface Create(GameServerHandler handler) {
    long cPtr = nlibJNI.GameServerFactory_Create(GameServerHandler.getCPtr(handler), handler);
    return (cPtr == 0) ? null : new GameServerInterface(cPtr, false);
  }

  public GameServerFactory() {
    this(nlibJNI.new_GameServerFactory(), true);
  }

}
