/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.awesomepiece.pl.swig;

public class GameConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GameConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GameConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nlibJNI.delete_GameConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHost(String value) {
    nlibJNI.GameConfig_host_set(swigCPtr, this, value);
  }

  public String getHost() {
    return nlibJNI.GameConfig_host_get(swigCPtr, this);
  }

  public void setPort(SWIGTYPE_p_uint32_t value) {
    nlibJNI.GameConfig_port_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getPort() {
    return new SWIGTYPE_p_uint32_t(nlibJNI.GameConfig_port_get(swigCPtr, this), true);
  }

  public void setLoss_mask(SWIGTYPE_p_std__vectorT_bool_t value) {
    nlibJNI.GameConfig_loss_mask_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_bool_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_bool_t getLoss_mask() {
    long cPtr = nlibJNI.GameConfig_loss_mask_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_bool_t(cPtr, false);
  }

  public void setLoss_rate(float value) {
    nlibJNI.GameConfig_loss_rate_set(swigCPtr, this, value);
  }

  public float getLoss_rate() {
    return nlibJNI.GameConfig_loss_rate_get(swigCPtr, this);
  }

  public GameConfig() {
    this(nlibJNI.new_GameConfig(), true);
  }

}
