#ifndef NLIB_NETWORK_DEFINE_H
#define NLIB_NETWORK_DEFINE_H

//#define MAX_NETWORK_ENDPOINTS_PER_THREAD 4;


#define MAX_MTU_SIZE 1024

#define NLIB_PROTOCOL_ID 0x41d93c7f

enum E_CLIENT_STATE_ID
{
	DISCONNECTED = 0,
	SENDING_CONNECTIN_REQUEST,
	SENDING_CONNECTIN_RESPONSE,
	CONNECTED,

	MAX_CLEINT_STATE_ID,
};

enum E_PACKET_ID
{
	CONNECTION_REQUEST = 0,
	CONNECTION_DENIED,
	CONNECTION_CHALLENGE,
	CONNECTION_RESPONSE,
	CONNECTION_KEEP_ALIVE,
	CONNECTION_PAYLOAD,
	CONNECTION_DISCONNECT,

	MAX_PACKET_ID,
};

enum E_TRANSPORT_TYPE
{
	UDP,
	TCP,
};

using byte = unsigned char;

#define NLIB_CONNECT_TOKEN_ENCRYPTED_LENGTH 896
#define NLIB_CHALLENGE_TOKEN_ENCRYPTED_LENGTH 300

#endif